name: Release Go project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
           # either 'goreleaser' (default) or 'goreleaser-pro'
           distribution: goreleaser
           # 'latest', 'nightly', or a semver
           version: '~> v2'
           args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}